### ISSUE TITLE
[zend-loader] Class 'Zend_Loader_PluginLoader' not found

### ISSUE THREAD

**Issue by glensc** [zf1s/zf1#10]
so, i've got another project which is broken with zf1s:

```
zf1s/zend-loader          1.12.22 Zend Framework 1 Loader package
```

```
PHP Stack trace:
PHP   1. {main}() bin/reports.php:0
...
PHP   6. Zend_View_Abstract->__construct() lib/Smarty.php:7
PHP   7. Zend_View_Abstract->setFilterPath() vendor/zf1s/zend-view/library/Zend/View/Abstract.php:153
PHP   8. Zend_View_Abstract->addFilterPath() vendor/zf1s/zend-view/library/Zend/View/Abstract.php:661
PHP   9. Zend_View_Abstract->_addPluginPath() vendor/zf1s/zend-view/library/Zend/View/Abstract.php:645
PHP  10. Zend_View_Abstract->getPluginLoader() vendor/zf1s/zend-view/library/Zend/View/Abstract.php:1133
```

but I think it worked with zf1/zend-loader.

may be related with these:
- https://github.com/zf1s/zend-loader/pull/2
- https://github.com/zf1s/zend-loader/pull/4

**Comment by falkenhawk** [comment]
Could you try with 1.13.0-rc.1, please? I pushed adjustments which should have solved all the loader conflicting issues in https://github.com/zf1s/zf1/commit/76477fbe00a198ef4376ea38c46df3960c574af8 - and report back if this is still valid?

**Comment by glensc** [comment]
yes. i'll try to trace back. too many annoying factors.

1. it's really hard to revert to zf1 namespace if you have zf1s packages installed. regardless what is in your composer.lock :). it's due the "replaces" zf1 constructs are still satisfied, so it would not try to "downgrade" to zf1 but leaves to zf1s. yes, `rm -rf vendor` always works, but trying to get to bottom of if how it's supposed to be done :)

2. I had my vendor from docker image not via volume. that might also create unexpected results, so not sure what version I had in the test :)

**Comment by glensc** [comment]
bogus report. works with:

```
zf1s/zend-loader          1.12.22 Zend Framework 1 Loader package
```

thanks for your patience.

**Comment by falkenhawk** [comment]
if Zend_Loader_PluginLoader class can't be found that's probably an issue with composer autoload being incorrectly generated (or interrupted?)... or having the composer autoloader being accidentally thrown out of the spl autoloader stack somewhere...
