### ISSUE TITLE
[zend-file-transfer]: unable to load adapters

### ISSUE THREAD

**Issue by glensc** [zf1s/zf1#11]
given code:
```php
<?php
require __DIR__ . '/vendor/autoload.php';
$file = new Zend_File_Transfer();
```

with `zf1s/zend-file-transfer` installed, i get error:
```
PHP Fatal error:  Uncaught Error: Class 'Zend_Loader' not found in vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer.php:67
Stack trace:
#0 vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer.php(54): Zend_File_Transfer->setAdapter('Http', false, Array)
#1 test.php(5): Zend_File_Transfer->__construct()
#2 {main}
  thrown in vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer.php on line 67
```

loading `"zf1s/zend-loader"`, the error changes to:

```
PHP Warning:  include_once(Http.php): failed to open stream: No such file or directory in vendor/zf1s/zend-loader/library/Zend/Loader.php on line 134
PHP Stack trace:
PHP   1. {main}() test.php:0
PHP   2. Zend_File_Transfer->__construct() test.php:5
PHP   3. Zend_File_Transfer->setAdapter() vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer.php:54
PHP   4. Zend_Loader::loadClass() vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer.php:72
PHP   5. Zend_Loader::loadFile() vendor/zf1s/zend-loader/library/Zend/Loader.php:82
```

I've created gist to play around with:
https://gist.github.com/glensc/ce6a301ddc60a0d1dba8878ae32709c3

with git tags `v1` and `v2` respectively for the tests.

**Comment by glensc** [comment]
some thoughts: as constructor calls `setAdapter` unconditionally:
- https://github.com/zf1s/zf1/blob/1.13.0/packages/zend-file-transfer/library/Zend/File/Transfer.php#L54

which calls `Zend_Loader` unconditionally:
- https://github.com/zf1s/zf1/blob/1.13.0/packages/zend-file-transfer/library/Zend/File/Transfer.php#L67

`zend-loader` should be added as package dependency.

**Comment by glensc** [comment]
the current code ends up calling `Zend_Loader::loadClass(Http)` because `$adapter = 'Zend_File_Transfer_Adapter_' . ucfirst($adapter);` is never assigned.

```php
    public function setAdapter($adapter, $direction = false, $options = array())
    {
        if (Zend_Loader::isReadable('Zend/File/Transfer/Adapter/' . ucfirst($adapter). '.php')) {
            $adapter = 'Zend_File_Transfer_Adapter_' . ucfirst($adapter);
        }

        if (!class_exists($adapter)) {
            Zend_Loader::loadClass($adapter);
        }
```

- https://github.com/zf1s/zf1/blob/1.13.0/packages/zend-file-transfer/library/Zend/File/Transfer.php#L67-L73

**Comment by falkenhawk** [comment]
looks like I missed that one... it should probably be: (similar to the changes in https://github.com/zf1s/zf1/blob/master/packages/zend-translate/library/Zend/Translate.php#L130)
```php
        if (class_exists('Zend_File_Transfer_Adapter_' . ucfirst($adapter)) {
            $adapter = 'Zend_File_Transfer_Adapter_' . ucfirst($adapter);
        }

        if (!class_exists($adapter)) {
            Zend_Loader::loadClass($adapter);
        }
```

**Comment by glensc** [comment]
was not sure what was the purpose of the `Zend_Loader::isReadable`, so I came up with https://github.com/zf1s/zf1/pull/12

**Comment by glensc** [comment]
ok, updated #12; however the code now runs without "zf1s/zend-loader" (see `v3` tag in gist)

**Comment by glensc** [comment]
oh, btw, don't link to branches!
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
- hit `y`
- and perhaps https://github.com/josephfrazier/octopermalinker

**Comment by glensc** [comment]
ironically, I don't even need to use that component. it was loaded but never used in the codebase.

so no pressure from my side to get this released :D

**Comment by falkenhawk** [comment]
I am going to wait a bit with the next release, in case of other issues occur in the meantime to avoid bumping versions for all components too often. If anyone needs to use this please switch to `@dev` version for now.

**Comment by glensc** [comment]
and as you said you missed this one: https://github.com/zf1s/zf1/issues/11#issuecomment-509661043

should probably inspect codebase for more of the adapter loading and check their compatibility.
