### ISSUE TITLE
Session Savehandler DbTable Warning

### ISSUE THREAD

**Issue by avonarb** [zf1s/zf1#23]
I am using zf1s 1.13.1 on PHP 7.4.8 and Zend_Session_SaveHandler_DbTable.

I get a warning:

"Warning: session_write_close(): Failed to write session data (user)."

The issue is described here i think:
https://github.com/zendframework/zf1/issues/665

Warning happens if you have 2 requests within a second without change of session data. Then, the modified information is unchanged (same timestamp) and the update call has 0 rows changed, which is not an error in this case.

Possible patch for Zend_Session_SaveHandler_DbTable is:
```

    public function write($id, $data)
    {
        $data = array($this->_modifiedColumn => time(),
                      $this->_dataColumn     => (string) $data);

        $rows = call_user_func_array(array(&$this, 'find'), $this->_getPrimary($id));

        if (count($rows)) {
            $data[$this->_lifetimeColumn] = $this->_getLifetime($rows->current());
            $this->update($data, $this->_getPrimary($id, self::PRIMARY_TYPE_WHERECLAUSE));
        } else {
            $data[$this->_lifetimeColumn] = $this->_lifetime;
            $this->insert(array_merge($this->_getPrimary($id, self::PRIMARY_TYPE_ASSOC), $data));
        }

        return true;
    }
```

**Comment by falkenhawk** [comment]
it would be lovely if you could transform your fix into a PR and add a test... if you find time of course
Is it the same as in https://github.com/zendframework/zf1/pull/654 ?
