### ISSUE TITLE
publish monorepo composer package

### ISSUE THREAD

**Issue by glensc** [zf1s/zf1#57]
It seems that `zf1s/zf1` is not registered on packagist.org:

```
$ composer require zf1s/zf1
  [InvalidArgumentException]
  Could not find a matching version of package zf1s/zf1. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```

This would help people installing "full zf1":
- https://github.com/zf1s/zf1/issues/51#issuecomment-774701307

project readme must be also updated, when this installation method works.

**Comment by falkenhawk** [comment]
I am not sure if I would like to do this, I am afraid it misses the whole point of the split components and less overhead compared to checking out the whole framework.
Moreover it may require additional maintenance and qa 🤔
I am not sure if it would easily workaround the issue reported in https://github.com/zf1s/zf1/issues/51#issuecomment-774701307 if composer is not available on that project - then having the whole framework package published on packagist does not help much, does it?
Perhaps the maintainer of that project could checkout the zf1 repo directly and use it in his project? 🤔

**Comment by falkenhawk** [comment]
Also if composer autoloader is not available there, then a separate, custom autoloader solution would be needed there which would load the files from individual `packages/zend-*/library/Zend` folders as there is no longer a single "root" folder which allows a PSR-0 autoloader to handle it (in contrary to https://github.com/Shardj/zf1-future/tree/master/library/Zend)

**Comment by glensc** [comment]
@falkenhawk it would be a package that has all dependencies installed. like symfony has. would be a solution to developers who are ok with composer, but not with identifying which packages are needed.

**Comment by falkenhawk** [comment]
After thinking about it for more that a year, we decided to stick to our past decision not to publish the whole package `zf1s/zf1` on packagist. Devs should be encouraged to install individual components, if necessary, and keep jumping off the ship in small steps 🙈 reducing dependencies to zf1 one by one.

Keep in mind, this whole thing was not meant to provide long-term support for zf1, only to allow working on legacy projects on more modern systems, while opening the possibility to migrate away from it, one component at a time.

Having everything split to single components should not be undermined by easy and lazy option to install the whole at once ;) 

Also, we do not want to bring in another official "full" package to packagist, introducing more confusion - which one to install, how would that relate to individual packages etc.

With all that said, it is still easy to install it for dev purposes / manual testing / transition period, by adding that to your `composer.json`:
```json
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/zf1s/zf1.git"
        }
    ]
```
this will allow to install `zf1s/zf1` from any branch or tagged version. e.g.
```
composer require zf1s/zf1:1.14.0
```
or `zf1s/zf1:dev-loader-overhauled-again`, `zf1s/zf1:dev-master` etc...
